# Generated by Django 3.1 on 2021-03-14 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_classification', '0003_auto_20210312_2154'),
        ('api_movie_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('deleted_at', models.DateField(auto_now=True)),
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_movie', models.CharField(max_length=100, unique=True)),
                ('launch_year', models.IntegerField()),
                ('sinopsis', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='api_movie_category.moviecategory')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='api_classification.classification')),
            ],
            options={
                'verbose_name': 'Pelicula',
                'verbose_name_plural': 'Peliculas',
                'db_table': 'tbl_movies',
                'ordering': ['movie_id'],
            },
        ),
    ]
