# Generated by Django 3.1.3 on 2021-01-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_movie', models.CharField(max_length=100)),
                ('lauch_year', models.CharField(max_length=4)),
                ('sinopsis', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Pelicula',
                'verbose_name_plural': 'Peliculas',
                'db_table': 'tbl_movies',
                'ordering': ['movie_id'],
                'managed': False,
            },
        ),
    ]
