# Generated by Django 3.1.3 on 2021-01-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('category_desc', models.CharField(blank=True, default='Sin descripción', max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'tbl_movie_category',
                'ordering': ['category_id'],
                'managed': False,
            },
        ),
    ]
