# Generated by Django 3.1.3 on 2021-01-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('classification_id', models.AutoField(primary_key=True, serialize=False)),
                ('classification_name', models.CharField(max_length=3)),
                ('classification_desc', models.CharField(blank=True, default='Sin descripción', max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Clasificación',
                'verbose_name_plural': 'Clasificaciones',
                'db_table': 'tbl_classification',
                'ordering': ['classification_id'],
                'managed': False,
            },
        ),
    ]
