# Generated by Django 3.1 on 2021-03-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('deleted_at', models.DateField(auto_now=True)),
                ('classification_id', models.AutoField(primary_key=True, serialize=False)),
                ('classification_name', models.CharField(max_length=3)),
                ('classification_desc', models.CharField(blank=True, max_length=250, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Clasificación',
                'verbose_name_plural': 'Clasificaciones',
                'db_table': 'tbl_classification',
                'ordering': ['classification_id'],
            },
        ),
    ]
