# Generated by Django 3.1 on 2021-03-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_classification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='classification_desc',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
